-- TRUNCATE TABLE "BaseQuestions" RESTART IDENTITY CASCADE;
-- TRUNCATE TABLE "SpecialQuestions" RESTART IDENTITY CASCADE;
-- TRUNCATE TABLE "BaseAnswers" RESTART IDENTITY CASCADE;
-- TRUNCATE TABLE "SpecialAnswers" RESTART IDENTITY CASCADE;
-- TRUNCATE TABLE "Users" RESTART IDENTITY CASCADE;


-- SELECT * FROM "SpecialAnswers"; 
